//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcPodstawy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminyLotow
    {
        public int Id { get; set; }
        public System.DateTime DataPrzylotu { get; set; }
        public System.DateTime DataOdlotu { get; set; }
        public string Lotnisko { get; set; }
        public string Miasto { get; set; }
    }
}
