//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace orm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wpisy
    {
        public int Id { get; set; }
        public string Tresc { get; set; }
    }
}
