<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="SA.Default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form" runat="server">
        <asp:ScriptManager ID="menadżer" runat="server"></asp:ScriptManager>
        <div>
            <asp:UpdatePanel runat="server">
                <ContentTemplate>
                    <asp:ObjectDataSource ID="źródłoDanych" runat="server" DeleteMethod="Delete" InsertMethod="Insert" OldValuesParameterFormatString="original_{0}" SelectMethod="GetData" TypeName="SA.DataSetTableAdapters.LotyTableAdapter" UpdateMethod="Update">
                        <InsertParameters>
                            <asp:Parameter DbType="Guid" Name="Id" />
                            <asp:Parameter Name="PortDocelowy" Type="String" />
                            <asp:Parameter Name="CenaBezRabatu" Type="Decimal" />
                            <asp:Parameter Name="CenaZRabatem" Type="Decimal" />
                            <asp:Parameter Name="Data" Type="DateTime" />
                        </InsertParameters>
                        <UpdateParameters>
                            <asp:Parameter DbType="Guid" Name="Id" />
                            <asp:Parameter Name="PortDocelowy" Type="String" />
                            <asp:Parameter Name="CenaBezRabatu" Type="Decimal" />
                            <asp:Parameter Name="CenaZRabatem" Type="Decimal" />
                            <asp:Parameter Name="Data" Type="DateTime" />
                            <asp:Parameter DbType="Guid" Name="Original_Id" />
                        </UpdateParameters>
                    </asp:ObjectDataSource>
                    <asp:GridView ID="grid" DataSourceID="źródłoDanych" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" runat="server" AutoGenerateColumns="False" DataKeyNames="Id">
                        <Columns>
                            <asp:BoundField DataField="Id" HeaderText="Id" ReadOnly="True" SortExpression="Id" />
                            <asp:BoundField DataField="PortDocelowy" HeaderText="PortDocelowy" SortExpression="PortDocelowy" />
                            <asp:BoundField DataField="CenaBezRabatu" HeaderText="CenaBezRabatu" SortExpression="CenaBezRabatu" />
                            <asp:BoundField DataField="CenaZRabatem" HeaderText="CenaZRabatem" SortExpression="CenaZRabatem" />
                            <asp:BoundField DataField="Data" HeaderText="Data" SortExpression="Data" />
                        </Columns>
                    </asp:GridView>
                    <asp:TextBox ID="poleMiasta" runat="server"></asp:TextBox>
                    <asp:Button ID="przyciskDodawania" Text="Dodaj" OnClick="przyciskDodawania_Click" runat="server"></asp:Button>
                </ContentTemplate>
            </asp:UpdatePanel>
        </div>
    </form>
</body>
</html>
