//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KółkoIKrzyżyk.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DługośćBokuPlanszy {
            get {
                return ((int)(this["DługośćBokuPlanszy"]));
            }
            set {
                this["DługośćBokuPlanszy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ZwycięskaLiczbaPól {
            get {
                return ((int)(this["ZwycięskaLiczbaPól"]));
            }
            set {
                this["ZwycięskaLiczbaPól"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int GłębokośćRekurencji {
            get {
                return ((int)(this["GłębokośćRekurencji"]));
            }
            set {
                this["GłębokośćRekurencji"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SiVsSi")]
        public global::KółkoIKrzyżyk.TrybGry TrybGry {
            get {
                return ((global::KółkoIKrzyżyk.TrybGry)(this["TrybGry"]));
            }
            set {
                this["TrybGry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gracz")]
        public global::KółkoIKrzyżyk.Zaczynający Zaczynający {
            get {
                return ((global::KółkoIKrzyżyk.Zaczynający)(this["Zaczynający"]));
            }
            set {
                this["Zaczynający"] = value;
            }
        }
    }
}
