//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace razorĆwiczenia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public string Miasto { get; set; }
        public string Kraj { get; set; }
        public Nullable<int> Ocena { get; set; }
        public string Zdjęcie { get; set; }
    }
}
